version: "3.9"
services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://root:r0O7@mongo:27017/mibd?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=r0O7
      - MONGO_INITDB_DATABASE=mibd
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
